# Generated by Django 4.2.1 on 2023-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_detect', '0004_alter_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='id_number',
        ),
    ]
